'use strict';

// Machine-readable error codes for API clients (iOS/Android/Web)
// Used alongside human-readable `error` strings in JSON responses

const ERROR_CODES = {
  // Auth
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  MAX_USERS_REACHED: 'MAX_USERS_REACHED',
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REFRESH_FAILED: 'TOKEN_REFRESH_FAILED',
  DEVICE_DEREGISTERED: 'DEVICE_DEREGISTERED',

  // Validation
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_FIELD: 'MISSING_FIELD',
  TOO_LONG: 'TOO_LONG',
  INVALID_FORMAT: 'INVALID_FORMAT',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',

  // Profiles
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  MAX_PROFILES: 'MAX_PROFILES',
  INVALID_PICK: 'INVALID_PICK',
  INVALID_NOTE: 'INVALID_NOTE',
  INVALID_REMINDER: 'INVALID_REMINDER',
  INVALID_LIVE_STATUS: 'INVALID_LIVE_STATUS',

  // Festival
  FESTIVAL_NOT_FOUND: 'FESTIVAL_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Export
  EXPORT_BUSY: 'EXPORT_BUSY',
  EXPORT_COOLDOWN: 'EXPORT_COOLDOWN',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',

  // Mobile / device tokens
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_PLATFORM: 'INVALID_PLATFORM',

  // WebSocket
  WS_AUTH_FAILED: 'WS_AUTH_FAILED',
  WS_ROOM_FULL: 'WS_ROOM_FULL',
  WS_RATE_LIMITED: 'WS_RATE_LIMITED',
  WS_JOIN_REQUIRED: 'WS_JOIN_REQUIRED',
  WS_INVALID_EVENT: 'WS_INVALID_EVENT',

  // Storage
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  STORAGE_CORRUPT: 'STORAGE_CORRUPT',
  STORAGE_WRITE_FAILED: 'STORAGE_WRITE_FAILED',

  // Notifications / push
  PUSH_TOKEN_INVALID: 'PUSH_TOKEN_INVALID',
  PUSH_DELIVERY_FAILED: 'PUSH_DELIVERY_FAILED',
  PUSH_NOT_CONFIGURED: 'PUSH_NOT_CONFIGURED',
  PUSH_DND_ACTIVE: 'PUSH_DND_ACTIVE',
  PUSH_USER_DISABLED: 'PUSH_USER_DISABLED',

  // Pagination
  INVALID_CURSOR: 'INVALID_CURSOR',
  PAGE_SIZE_EXCEEDED: 'PAGE_SIZE_EXCEEDED',

  // Avatar
  AVATAR_TOO_LARGE: 'AVATAR_TOO_LARGE',
  AVATAR_INVALID_FORMAT: 'AVATAR_INVALID_FORMAT',
  AVATAR_DIMENSIONS_EXCEEDED: 'AVATAR_DIMENSIONS_EXCEEDED',

  // Conflict
  CONFLICT: 'CONFLICT',
  VERSION_MISMATCH: 'VERSION_MISMATCH',
};

module.exports = { ERROR_CODES };
