// Expo config plugin: inject a `release` signingConfig into the generated
// android/app/build.gradle so CI (GitHub Actions) can sign the release AAB with
// our Play **upload** key instead of the debug keystore.
//
// Why this exists: android/ is gitignored and regenerated by `expo prebuild`, and
// the React Native template signs the `release` buildType with the *debug*
// keystore. EAS used to inject the real upload key for us; off-EAS we have to do
// it ourselves. This plugin rewrites build.gradle at prebuild time to add a
// signingConfig that reads its credentials from gradle.properties:
//
//   MYAPP_UPLOAD_STORE_FILE      (path to the .keystore, relative to android/app)
//   MYAPP_UPLOAD_STORE_PASSWORD
//   MYAPP_UPLOAD_KEY_ALIAS
//   MYAPP_UPLOAD_KEY_PASSWORD
//
// The CI workflow (.github/workflows/android-release.yml) decodes the keystore
// secret to a file and writes those four properties into android/gradle.properties.
//
// IMPORTANT: the injected signingConfig is guarded at *Gradle eval time* by
// `project.hasProperty('MYAPP_UPLOAD_STORE_FILE')`. When the property is absent
// (local dev builds, EAS builds), release falls back to the debug signingConfig
// exactly as the stock template does — so this plugin is a no-op for everyone
// except a build that has explicitly provided the upload credentials.
//
// The plugin itself is idempotent: if the marker is already present it leaves the
// file untouched, so re-running prebuild won't duplicate the block.

const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = '// @generated:withAndroidUploadSigning';

// The signingConfigs entry we add. Reads from gradle.properties; the path is
// resolved relative to android/app (storeFile uses a File so a relative path is
// taken from the module dir).
const SIGNING_CONFIG_BLOCK = `        release {
            ${MARKER}
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
`;

/**
 * Insert a `release { ... }` entry inside the existing `signingConfigs { ... }`
 * block, right after the `debug { ... }` entry that the RN template ships.
 */
function addReleaseSigningConfig(contents) {
  // Match the template's debug signingConfig and append our release block after
  // its closing brace. The template looks like:
  //   signingConfigs {
  //       debug {
  //           ...
  //       }
  //   }
  const debugBlock = /signingConfigs\s*\{[\s\S]*?debug\s*\{[\s\S]*?\n(\s*)\}\n/;
  const match = contents.match(debugBlock);
  if (!match) {
    throw new Error(
      'withAndroidUploadSigning: could not find the signingConfigs { debug { } } block ' +
        'in android/app/build.gradle to anchor the release signingConfig.',
    );
  }
  const insertAt = match.index + match[0].length;
  return contents.slice(0, insertAt) + SIGNING_CONFIG_BLOCK + contents.slice(insertAt);
}

/**
 * Point buildTypes.release at the release signingConfig *only when* the upload
 * credentials are present; otherwise keep the template's debug signingConfig so
 * local/EAS builds are unaffected.
 */
function pointReleaseBuildType(contents) {
  // Stock template line inside `buildTypes { release { ... } }`:
  //   signingConfig signingConfigs.debug
  // Replace the first such line (the one in the release buildType) with a
  // conditional that prefers release when configured.
  const releaseBuildType = /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/;
  if (!releaseBuildType.test(contents)) {
    throw new Error(
      'withAndroidUploadSigning: could not find `signingConfig signingConfigs.debug` ' +
        'inside buildTypes.release to retarget.',
    );
  }
  return contents.replace(
    releaseBuildType,
    `$1signingConfig project.hasProperty('MYAPP_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`,
  );
}

const withAndroidUploadSigning = (config) => {
  // SAFETY GATE: only modify build.gradle when explicitly enabled (set by
  // .github/workflows/android-release.yml). For every other prebuild — EAS
  // builds, the android-e2e job, local dev — this is a no-op, so the stock
  // template (and EAS's own release signing) is left completely untouched.
  if (process.env.ANDROID_GH_SIGNING !== '1') return config;
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        'withAndroidUploadSigning is only compatible with Groovy build.gradle (got ' + cfg.modResults.language + ').',
      );
    }
    // Idempotent: bail if we've already injected the block.
    if (cfg.modResults.contents.includes(MARKER)) {
      return cfg;
    }
    let contents = cfg.modResults.contents;
    contents = addReleaseSigningConfig(contents);
    contents = pointReleaseBuildType(contents);
    cfg.modResults.contents = contents;
    return cfg;
  });
};

module.exports = withAndroidUploadSigning;
